server:
  port: 9999

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB

  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1998

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        hbm2ddl.auto: update

